<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Custom\Middleware\" />
    <Folder Include="Custom\Filters\" />
    <Folder Include="Entities\Models\" />
    <Folder Include="Entities\DTO\" />
    <Folder Include="Database\" />
    <Folder Include="Contract\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
