// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250503101529_Employee Table")]
    partial class EmployeeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7416f782-d3f9-4266-8cf4-3aaacdb51046"),
                            Age = 25,
                            Email = "omdwivedy@business.com",
                            Name = "Omkareshwar Dwivedy",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee2e08a9-66b1-47fc-be8d-398c1192d389"),
                            DateCreated = new DateTime(2025, 5, 3, 15, 45, 29, 109, DateTimeKind.Local).AddTicks(8668),
                            IsCompleted = false,
                            Title = "Configure EF seed data"
                        },
                        new
                        {
                            Id = new Guid("9acf1bfb-eca7-42cb-885e-dab9d777b533"),
                            DateCreated = new DateTime(2025, 5, 3, 15, 45, 29, 109, DateTimeKind.Local).AddTicks(8689),
                            IsCompleted = false,
                            Title = "Make your first GET request"
                        },
                        new
                        {
                            Id = new Guid("1c12bbb0-174d-44fb-bd3a-2837d43a2236"),
                            DateCreated = new DateTime(2025, 5, 3, 15, 45, 29, 109, DateTimeKind.Local).AddTicks(8714),
                            IsCompleted = false,
                            Title = "Test your first GET request"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
