// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250508052900_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            Email = "aman.ojha@test.com",
                            Name = "Aman Ojha",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            Email = "ravina.ghidode@test.com",
                            Name = "Ravina Ghidode",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            Email = "gagan.sharma@test.com",
                            Name = "Gagan Sharma",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            Age = 27,
                            Email = "mayank.joshi@test.com",
                            Name = "Mayank Joshi",
                            Role = 2
                        },
                        new
                        {
                            Id = 5,
                            Age = 29,
                            Email = "satyam.chouksey@test.com",
                            Name = "Satyam Chouksey",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            Age = 25,
                            Email = "niharika.gupta@test.com",
                            Name = "Niharika Gupta",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            Age = 25,
                            Email = "praduman.dwivedy@test.com",
                            Name = "Prduman Dwivedy",
                            Role = 4
                        });
                });

            modelBuilder.Entity("Entities.Models.EmployeeProjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 4,
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 5,
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 6,
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 7,
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 7,
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 7,
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 7,
                            ProjectId = 4
                        });
                });

            modelBuilder.Entity("Entities.Models.EmployeeSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SkillId");

                    b.ToTable("EmployeeSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 2,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 2,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 3,
                            SkillId = 9
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 3,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 4,
                            SkillId = 9
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 4,
                            SkillId = 10
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 5,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 5,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 6,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = 7,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 13,
                            EmployeeId = 7,
                            SkillId = 8
                        });
                });

            modelBuilder.Entity("Entities.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "REX-Replatform"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Omnia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Levvia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DocTime"
                        });
                });

            modelBuilder.Entity("Entities.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 4,
                            Name = "React"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tosca"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Selenium"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Linux"
                        },
                        new
                        {
                            Id = 10,
                            Name = "SonarQube"
                        });
                });

            modelBuilder.Entity("Entities.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d4d1494-6e65-4ee9-bf7f-baadc2c5f84f"),
                            DateCreated = new DateTime(2025, 5, 8, 10, 58, 59, 820, DateTimeKind.Local).AddTicks(6822),
                            IsCompleted = false,
                            Title = "Configure EF seed data"
                        },
                        new
                        {
                            Id = new Guid("3428c86b-ec18-42fe-9158-e813f2d0c538"),
                            DateCreated = new DateTime(2025, 5, 8, 10, 58, 59, 820, DateTimeKind.Local).AddTicks(6834),
                            IsCompleted = false,
                            Title = "Make your first GET request"
                        },
                        new
                        {
                            Id = new Guid("9c87b694-ef74-454f-b583-3e9bfba781d9"),
                            DateCreated = new DateTime(2025, 5, 8, 10, 58, 59, 820, DateTimeKind.Local).AddTicks(6835),
                            IsCompleted = false,
                            Title = "Test your first GET request"
                        });
                });

            modelBuilder.Entity("Entities.Models.EmployeeProjects", b =>
                {
                    b.HasOne("Entities.Models.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Entities.Models.EmployeeSkills", b =>
                {
                    b.HasOne("Entities.Models.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Navigation("EmployeeProjects");

                    b.Navigation("EmployeeSkills");
                });

            modelBuilder.Entity("Entities.Models.Project", b =>
                {
                    b.Navigation("EmployeeProjects");
                });

            modelBuilder.Entity("Entities.Models.Skill", b =>
                {
                    b.Navigation("EmployeeSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
