// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Database;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7942ea38-6b67-4e69-86c5-e1d6919baf59"),
                            DateCreated = new DateTime(2024, 12, 31, 15, 39, 41, 948, DateTimeKind.Local).AddTicks(280),
                            IsCompleted = false,
                            Title = "Configure EF seed data"
                        },
                        new
                        {
                            Id = new Guid("c6436da2-d38f-4898-b085-59632f8acc94"),
                            DateCreated = new DateTime(2024, 12, 31, 15, 39, 41, 948, DateTimeKind.Local).AddTicks(291),
                            IsCompleted = false,
                            Title = "Make your first GET request"
                        },
                        new
                        {
                            Id = new Guid("db3c17a7-a315-49c1-bba1-66f8a4a50425"),
                            DateCreated = new DateTime(2024, 12, 31, 15, 39, 41, 948, DateTimeKind.Local).AddTicks(292),
                            IsCompleted = false,
                            Title = "Test your first GET request"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
